#* For a pull request, we use the PR title. After a push (probably to main), we use the commit title.
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message || github.event.pull_request.title }}

#* To avoid duplicate jobs running when both push and PR is satisfied, we use this:
#* https://github.com/orgs/community/discussions/26940#discussioncomment-5686753
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

#* Stop stale workflows when pull requests are updated: https://stackoverflow.com/a/70972844
#* Does not apply to the main branch.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build default
        run: |
          cd test
          cmake --workflow --preset default
      - name: Remove output folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: out
      - name: Build split
        run: |
          cd test
          cmake --workflow --preset split

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build default
        run: |
          cd test
          cmake --workflow --preset default
      - name: Remove output folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: out
      - name: Build split
        run: |
          cd test
          cmake --workflow --preset split

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build default
        run: |
          cd test
          cmake --workflow --preset default
      - name: Remove output folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: out
      - name: Build split
        run: |
          cd test
          cmake --workflow --preset split
